blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ General Question / Discussion
    url: https://github.com/cpro-capstone-290x/TaskPal.git/discussions
    about: Ask questions or start a discussion about the project

issue_template:
  - name: ğŸ Bug Report
    description: Report an error or unexpected behavior
    file: bug_report.md
  - name: ğŸ’¡ Feature Request
    description: Suggest a new idea or feature enhancement
    file: feature_request.md
  - name: âš™ï¸ Development Task
    description: Track internal technical or refactoring tasks
    file: task_template.md
